version: '3'

services:
  db:
    image: postgres:12-alpine
    container_name: dbpf
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=portfolio
    ports:
    - 5433:5432
    volumes:
    - data:/var/lib/postgresql/data
     
  backend:
    build: ./backend
    environment:
      - PORT=80
      - SECRET_KEY=hushush
      - BASE_URL=http://localhost:9091
      - DATABASE_URL=postgresql://portfolio:portfolio@db:5432/portfolio
      - ALLOWED_HOSTS=*
      - CORS_ORIGIN_WHITELIST=http://localhost:8080,http://localhost:9091,http://academie.my-wan.de
    ports:
      - 9095:80
    volumes:  
      - mediafiles:/mediafiles  
    depends_on:
      - db
            


volumes:
  data:
  mediafiles:
  
