version: '3'

services:
  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=portfolio
    ports:
    - 5432:5432
    volumes:
    - data:/var/lib/postgresql/data
     

volumes:
  data:
  
