version: '3'

services:
  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=portfolio
    ports:
    - 5432:5432
    volumes:
    - data:/var/lib/postgresql/data
     
  backend:
    build: ./backend
    environment:
      - PORT=80
      - SECRET_KEY=hushush
      - BASE_URL=http://localhost:9091
      - DATABASE_URL=postgresql://portfolio:portfolio@db:5432/portfolio
      - ALLOWED_HOSTS=*
      - CORS_ORIGIN_WHITELIST=http://localhost:8080,http://localhost:9091
    ports:
      - 9090:80
    volumes:  
      - mediafiles:/mediafiles  
    depends_on:
      - db
            
  frontend:
    build:
      context: ./frontend
      args:
        #- BASE_URL=https://mapariel.dd-dns.de
        #- BASE_API=https://mapariel.dd-dns.de/api/
        - BASE_URL=http://localhost:9091
        - BASE_API=http://localhost:9091/api/
      
    ports:
      - 9091:80
    volumes:
      - mediafiles:/usr/share/nginx/mediafiles            
    environment:
      - PORT=80
    depends_on:
      - backend



volumes:
  data:
  mediafiles:
  
