version: '3'

services:
  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=portfolio
    ports:
    - 5432:5432
    volumes:
    - data:/var/lib/postgresql/data
     
  backend:
    build: .
    environment:
      - PORT=80
      - SECRET_KEY=hushush
      - DATABASE_URL=postgresql://portfolio:portfolio@db:5432/portfolio
      - ALLOWED_HOSTS=*
    ports:
      - 9090:80
    depends_on:
      - db      
     


volumes:
  data:
  