# Generated by Django 4.0 on 2021-12-27 05:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_brief', models.TextField(default='short description', max_length=256)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('source', models.URLField(blank=True)),
                ('technology', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='img')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
